CREATE TABLE ATTACHMENTS (
  ID INT NOT NULL AUTO_INCREMENT,
  PATH VARCHAR(255) NOT NULL,
  FILE_NAME VARCHAR(100) NOT NULL,
  CORTE_ID INT NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (CORTE_ID) REFERENCES CORTES(ID)
);

ALTER TABLE TALLES ADD COLUMN finalization_date DATE NULL;

CREATE TABLE OPERATORS (
  ID INT NOT NULL AUTO_INCREMENT,
  USERNAME VARCHAR(25) NOT NULL,
  PASSWORD VARCHAR(250) NULL,
  SALT VARCHAR(250) NULL,
  DESCRIPTION VARCHAR(125) NULL,
  ROL VARCHAR(25) NOT NULL,
  PRIMARY KEY (ID)
);