-- Primero manejo los talles
ALTER TABLE TALLES MODIFY quantity INT;
ALTER TABLE TALLES MODIFY clothes_delivered INT;
ALTER TABLE TALLES MODIFY first_due_date DATE;
ALTER TABLE TALLES MODIFY second_due_date DATE;

UPDATE TALLES SET ESTADO = 6 WHERE ESTADO = 7;

-- Luego los cortes
ALTER TABLE CORTES MODIFY clothes_quantity INT;
ALTER TABLE CORTES MODIFY due_date DATE;

UPDATE CORTES SET ESTADO = 5 WHERE ESTADO = 6;
UPDATE CORTES SET ESTADO = 6 WHERE ESTADO = 7;
UPDATE CORTES SET ESTADO = 8 WHERE ESTADO = 9;

-- despues los talleres
UPDATE TALLERES SET ESTADO = 3 WHERE ESTADO = 4;

-- LO ULITMO QUE HAY QUE CORRER
UPDATE ESTADOS SET COLOR = 'navy' WHERE ID = 1;
UPDATE ESTADOS SET COLOR = 'lime' WHERE ID = 2;
UPDATE ESTADOS SET NAME = 'En produccion' WHERE ID = 3;
UPDATE ESTADOS SET NAME = 'No disponible', COLOR = 'maroon' WHERE ID = 4;
UPDATE ESTADOS SET NAME = 'Sin asignar', COLOR = '' WHERE ID = 5;
UPDATE ESTADOS SET NAME = 'En produccion', COLOR = 'blue' WHERE ID = 6;
UPDATE ESTADOS SET NAME = 'Cerrado con deudas', COLOR = 'yellow' WHERE ID = 7;
UPDATE ESTADOS SET NAME = 'Finalizado', COLOR = 'olive' WHERE ID = 8;
DELETE FROM ESTADOS WHERE ID = 9;